<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 300, align = "center"></a>

<h1 align=center><font size = 5>Assignment: Notebook for Peer Assignment</font></h1>

# Introduction

Using this Python notebook you will:
1. Understand 3 Chicago datasets  
1. Load the 3 datasets into 3 tables in a Db2 database
1. Execute SQL queries to answer assignment questions

## Understand the datasets 
To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:
1. <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2">Socioeconomic Indicators in Chicago</a>
1. <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t">Chicago Public Schools</a>
1. <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago
This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

For this assignment you will use a snapshot of this dataset which can be downloaded from:
https://ibm.box.com/shared/static/05c3415cbfbtfnr2fx4atenb2sd361ze.csv

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2



### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

For this assignment you will use a snapshot of this dataset which can be downloaded from:
https://ibm.box.com/shared/static/f9gjvj1gjmxxzycdhplzt01qtz0s7ew7.csv

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t




### 3. Chicago Crime Data 

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days. 

This dataset is quite large - over 1.5GB in size with over 6.5 million rows. For the purposes of this assignment we will use a much smaller sample of this dataset which can be downloaded from:
https://ibm.box.com/shared/static/svflyugsr9zbqy5bmowgswqemfpm1x7f.csv

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2

### Download the datasets
In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):
1. __CENSUS_DATA:__ https://ibm.box.com/shared/static/05c3415cbfbtfnr2fx4atenb2sd361ze.csv
1. __CHICAGO_PUBLIC_SCHOOLS__  https://ibm.box.com/shared/static/f9gjvj1gjmxxzycdhplzt01qtz0s7ew7.csv
1. __CHICAGO_CRIME_DATA:__ https://ibm.box.com/shared/static/svflyugsr9zbqy5bmowgswqemfpm1x7f.csv

__NOTE:__ Ensure you have downloaded the datasets using the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables
To analyze the data using SQL, it first needs to be stored in the database.

While it is easier to read the dataset into a Pandas dataframe and then PERSIST it into the database as we saw in Week 3 Lab 3, it results in mapping to default datatypes which may not be optimal for SQL querying. For example a long textual field may map to a CLOB instead of a VARCHAR. 

Therefore, __it is highly recommended to manually load the table using the database console LOAD tool, as indicated in Week 2 Lab 1 Part II__. The only difference with that lab is that in Step 5 of the instructions you will need to click on create "(+) New Table" and specify the name of the table you want to create and then click "Next". 

<img src = "https://ibm.box.com/shared/static/uc4xjh1uxcc78ks1i18v668simioz4es.jpg">

##### Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the first dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new tables as folows:
1. __CENSUS_DATA__
1. __CHICAGO_PUBLIC_SCHOOLS__
1. __CHICAGO_CRIME_DATA__

### Connect to the database 
Let us first load the SQL extension and establish a connection with the database

In [3]:
%load_ext sql

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance in first lab in Week 3. From the __uri__ field of your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src ="https://ibm.box.com/shared/static/hzhkvdyinpupm2wfx49lkr71q9swbpec.jpg">

In [4]:
# Remember the connection string is of the format:
# %sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name
# Enter the connection string for your Db2 on Cloud database instance below
%sql ibm_db_sa://wtf02561:qpbc6n64n61%40qkvq@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB

'Connected: wtf02561@BLUDB'

## Problems
Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table

In [6]:
# Rows in Crime table
%sql select count(*) from chicago_crime_data

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('533'),)]

### Problem 2

##### Retrieve first 10 rows from the CRIME table

In [13]:
%sql select * from chicago_crime_data  fetch first 100 rows only

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(3512276, 'HK587712', '08/28/2004 05:50:56 PM', '047XX S KEDZIE AVE', '890', 'THEFT', 'FROM BUILDING', 'SMALL RETAIL STORE', 'FALSE', 'FALSE', 911, 9, 14, 58, '6', 1155838, 1873050, 2004, '02/10/2018 03:50:01 PM', Decimal('41.80744050'), Decimal('-87.70395585'), '(41.8074405, -87.703955849)'),
 (3406613, 'HK456306', '06/26/2004 12:40:00 PM', '009XX N CENTRAL PARK AVE', '820', 'THEFT', '$500 AND UNDER', 'OTHER', 'FALSE', 'FALSE', 1112, 11, 27, 23, '6', 1152206, 1906127, 2004, '02/28/2018 03:56:25 PM', Decimal('41.89827996'), Decimal('-87.71640551'), '(41.898279962, -87.716405505)'),
 (8002131, 'HT233595', '04/04/2011 05:45:00 AM', '043XX S WABASH AVE', '820', 'THEFT', '$500 AND UNDER', 'NURSING HOME/RETIREMENT HOME', 'FALSE', 'FALSE', 221, 2, 3, 38, '6', 1177436, 1876313, 2011, '02/10/2018 03:50:01 PM', Decimal('41.81593313'), Decimal('-87.62464213'), '(41.815933131, -87.624642127)'),
 (7903289, 'HT133522', '12/30/2010 04:30:00 PM', '083XX S KINGSTON AVE', '840', 'THEFT', 'FINANCIAL ID THEFT: OVER $300', 'RESIDENCE', 'FALSE', 'FALSE', 423, 4, 7, 46, '6', 1194622, 1850125, 2010, '02/10/2018 03:50:01 PM', Decimal('41.74366532'), Decimal('-87.56246276'), '(41.743665322, -87.562462756)'),
 (10402076, 'HZ138551', '02/02/2016 07:30:00 PM', '033XX W 66TH ST', '820', 'THEFT', '$500 AND UNDER', 'ALLEY', 'FALSE', 'FALSE', 831, 8, 15, 66, '6', 1155240, 1860661, 2016, '02/10/2018 03:50:01 PM', Decimal('41.77345530'), Decimal('-87.70648047'), '(41.773455295, -87.706480471)'),
 (7732712, 'HS540106', '09/29/2010 07:59:00 AM', '006XX W CHICAGO AVE', '810', 'THEFT', 'OVER $500', 'PARKING LOT/GARAGE(NON.RESID.)', 'FALSE', 'FALSE', 1323, 12, 27, 24, '6', 1171668, 1905607, 2010, '02/10/2018 03:50:01 PM', Decimal('41.89644677'), Decimal('-87.64493868'), '(41.896446772, -87.644938678)'),
 (10769475, 'HZ534771', '11/30/2016 01:15:00 AM', '050XX N KEDZIE AVE', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 1713, 17, 33, 14, '6', 1154133, 1933314, 2016, '02/10/2018 03:50:01 PM', Decimal('41.97284491'), Decimal('-87.70860008'), '(41.972844913, -87.708600079)'),
 (4494340, 'HL793243', '12/16/2005 04:45:00 PM', '005XX E PERSHING RD', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 213, 2, 3, 38, '6', 1180448, 1879234, 2005, '02/28/2018 03:56:25 PM', Decimal('41.82387989'), Decimal('-87.61350386'), '(41.823879885, -87.613503857)'),
 (3778925, 'HL149610', '01/28/2005 05:00:00 PM', '100XX S WASHTENAW AVE', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 2211, 22, 19, 72, '6', 1160129, 1838040, 2005, '02/28/2018 03:56:25 PM', Decimal('41.71128051'), Decimal('-87.68917910'), '(41.711280513, -87.689179097)'),
 (3324217, 'HK361551', '05/13/2004 02:15:00 PM', '033XX W BELMONT AVE', '820', 'THEFT', '$500 AND UNDER', 'SMALL RETAIL STORE', 'FALSE', 'FALSE', 1733, 17, 35, 21, '6', 1153590, 1921084, 2004, '02/28/2018 03:56:25 PM', Decimal('41.93929582'), Decimal('-87.71092344'), '(41.939295821, -87.710923442)'),
 (9902691, 'HX552797', '12/23/2014 02:15:00 PM', '076XX S CICERO AVE', '860', 'THEFT', 'RETAIL THEFT', 'DEPARTMENT STORE', 'TRUE', 'FALSE', 833, 8, 13, 65, '6', 1145727, 1853720, 2014, '02/10/2018 03:50:01 PM', Decimal('41.75459296'), Decimal('-87.74152854'), '(41.754592961, -87.741528537)'),
 (7947964, 'HT180228', '02/26/2011 04:00:00 PM', '012XX S HALSTED ST', '820', 'THEFT', '$500 AND UNDER', 'BAR OR TAVERN', 'FALSE', 'FALSE', 1232, 12, 25, 28, '6', 1171230, 1894421, 2011, '02/10/2018 03:50:01 PM', Decimal('41.86576126'), Decimal('-87.64687598'), '(41.865761261, -87.646875977)'),
 (8568365, 'HV243612', '04/15/2012 07:30:00 PM', '108XX S EMERALD AVE', '820', 'THEFT', '$500 AND UNDER', 'RESIDENTIAL YARD (FRONT/BACK)', 'FALSE', 'FALSE', 2233, 22, 34, 49, '6', 1173239, 1832994, 2012, '02/04/2016 06:33:39 AM', Decimal('41.69715437'), Decimal('-87.64131567'), '(41.697154372, -87.641315669)'),
 (5343947, 'HN200365', '02/26/2007 04:00:00 PM', '011XX S CANAL ST', '842', 'THEFT', 'AGG: FINANCIAL ID THEFT', 'OTHER', 'FALSE', 'FALSE', 131, 1, 2, 28, '6', 1173307, 1895342, 2007, '02/28/2018 03:56:25 PM', Decimal('41.86824272'), Decimal('-87.63922391'), '(41.868242722, -87.639223912)'),
 (3121541, 'HK108680', '01/05/2003 06:30:00 PM', '038XX W FLOURNOY ST', '890', 'THEFT', 'FROM BUILDING', 'RESIDENCE PORCH/HALLWAY', 'FALSE', 'FALSE', 1133, 11, 24, 26, '6', 1150808, 1896753, 2003, '02/28/2018 03:56:25 PM', Decimal('41.87258418'), Decimal('-87.72178565'), '(41.872584178, -87.72178565)'),
 (10209850, 'HY396729', '08/24/2015 07:30:00 PM', '026XX N ELSTON AVE', '820', 'THEFT', '$500 AND UNDER', 'PARKING LOT/GARAGE(NON.RESID.)', 'FALSE', 'FALSE', 1432, 14, 1, 22, '6', 1160867, 1917657, 2015, '02/10/2018 03:50:01 PM', Decimal('41.92974382'), Decimal('-87.68427378'), '(41.929743818, -87.684273777)'),
 (6866556, 'HR271603', '04/16/2009 05:30:00 PM', '089XX S STONY ISLAND AVE', '860', 'THEFT', 'RETAIL THEFT', 'OTHER', 'TRUE', 'FALSE', 413, 4, 8, 48, '6', 1188475, 1846086, 2009, '02/28/2018 03:56:25 PM', Decimal('41.73273081'), Decimal('-87.58511413'), '(41.732730806, -87.585114125)'),
 (9681782, 'HX332132', '07/04/2014 09:45:00 PM', '079XX S STATE ST', '820', 'THEFT', '$500 AND UNDER', 'CTA PLATFORM', 'FALSE', 'FALSE', 623, 6, 6, 44, '6', 1177660, 1852569, 2014, '02/10/2018 03:50:01 PM', Decimal('41.75077211'), Decimal('-87.62453842'), '(41.750772111, -87.624538423)'),
 (9166453, 'HW303994', '06/04/2013 09:00:00 AM', '055XX W GLADYS AVE', '810', 'THEFT', 'OVER $500', 'VACANT LOT/LAND', 'FALSE', 'FALSE', 1522, 15, 29, 25, '6', 1139693, 1897797, 2013, '02/10/2018 03:50:01 PM', Decimal('41.87565911'), Decimal('-87.76256886'), '(41.875659108, -87.762568861)'),
 (7762423, 'HS569246', '10/17/2010 06:00:00 PM', '058XX W ARTHINGTON ST', '880', 'THEFT', 'PURSE-SNATCHING', 'SIDEWALK', 'FALSE', 'FALSE', 1513, 15, 29, 25, '6', 1137635, 1895420, 2010, '02/10/2018 03:50:01 PM', Decimal('41.86917360'), Decimal('-87.77018245'), '(41.869173601, -87.770182447)'),
 (10046030, 'HY234744', '04/24/2015 07:55:00 PM', '008XX N MICHIGAN AVE', '860', 'THEFT', 'RETAIL THEFT', 'DEPARTMENT STORE', 'TRUE', 'FALSE', 1833, 18, 42, 8, '6', 1177338, 1906213, 2015, '02/10/2018 03:50:01 PM', Decimal('41.89798294'), Decimal('-87.62409563'), '(41.897982937, -87.624095634)'),
 (6233210, 'HP320451', '05/06/2008 03:20:00 PM', '0000X S STATE ST', '860', 'THEFT', 'RETAIL THEFT', 'DEPARTMENT STORE', 'FALSE', 'FALSE', 123, 1, 42, 32, '6', 1176390, 1900234, 2008, '02/28/2018 03:56:25 PM', Decimal('41.88159770'), Decimal('-87.62775808'), '(41.881597699, -87.627758082)'),
 (5677874, 'HN484464', '07/22/2007 07:25:00 AM', '0000X E 69TH ST', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 322, 3, 20, 69, '6', 1178177, 1859290, 2007, '02/28/2018 03:56:25 PM', Decimal('41.76920358'), Decimal('-87.62244037'), '(41.769203583, -87.622440369)'),
 (11230490, 'JB151690', '02/14/2018 11:15:00 AM', '036XX S ARCHER AVE', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 912, 9, 11, 59, '6', 1161614, 1880357, 2018, '05/04/2018 03:51:04 PM', Decimal('41.82737375'), Decimal('-87.68256806'), '(41.827373751, -87.682568055)'),
 (7172285, 'HR582990', '10/11/2009 07:00:00 PM', '060XX S HALSTED ST', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 712, 7, 16, 68, '6', 1171999, 1865041, 2009, '02/04/2016 06:33:39 AM', Decimal('41.78512289'), Decimal('-87.64491718'), '(41.785122891, -87.644917177)'),
 (7125811, 'HR535632', '09/13/2009 10:30:00 PM', '044XX N ELSTON AVE', '820', 'THEFT', '$500 AND UNDER', 'ATHLETIC CLUB', 'FALSE', 'FALSE', 1722, 17, 39, 14, '6', 1148062, 1929262, 2009, '02/28/2018 03:56:25 PM', Decimal('41.96184525'), Decimal('-87.73102930'), '(41.961845248, -87.731029303)'),
 (2219750, 'HH486939', '07/03/2002 08:00:00 PM', '100XX W OHARE ST', '870', 'THEFT', 'POCKET-PICKING', 'AIRPORT/AIRCRAFT', 'FALSE', 'FALSE', 1651, 16, 41, 76, '6', 1100658, 1934241, 2002, '02/28/2018 03:56:25 PM', Decimal('41.97629041'), Decimal('-87.90522722'), '(41.976290414, -87.905227221)'),
 (9296677, 'HW441620', '09/07/2013 02:30:00 AM', '066XX S WESTERN AVE', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 832, 8, 15, 66, '6', 1161515, 1860616, 2013, '02/10/2018 03:50:01 PM', Decimal('41.77320400'), Decimal('-87.68347884'), '(41.773203996, -87.68347884)'),
 (2889910, 'HJ561433', '08/13/2003 08:00:00 PM', '104XX S HALSTED ST', '810', 'THEFT', 'OVER $500', 'PARKING LOT/GARAGE(NON.RESID.)', 'FALSE', 'FALSE', 2233, 22, 34, 73, '6', 1172824, 1835651, 2003, '02/28/2018 03:56:25 PM', Decimal('41.70445472'), Decimal('-87.64275716'), '(41.704454724, -87.642757155)'),
 (7173960, 'HR583513', '10/11/2009 05:00:00 PM', '079XX S PARNELL AVE', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 621, 6, 17, 44, '6', 1174008, 1852295, 2009, '02/10/2018 03:50:01 PM', Decimal('41.75010200'), Decimal('-87.63792916'), '(41.750101999, -87.637929163)'),
 (9859793, 'HX509438', '11/16/2014 02:30:00 PM', '002XX S MICHIGAN AVE', '890', 'THEFT', 'FROM BUILDING', 'OTHER', 'FALSE', 'FALSE', 113, 1, 42, 32, '6', 1177328, 1899333, 2014, '02/10/2018 03:50:01 PM', Decimal('41.87910409'), Decimal('-87.62434115'), '(41.879104092, -87.62434115)'),
 (7868443, 'HS681158', '12/21/2010 05:00:00 PM', '036XX S GILES AVE', '810', 'THEFT', 'OVER $500', 'APARTMENT', 'FALSE', 'FALSE', 212, 2, 2, 35, '6', 1178860, 1880905, 2010, '02/04/2016 06:33:39 AM', Decimal('41.82850160'), Decimal('-87.61927867'), '(41.828501601, -87.61927867)'),
 (3314082, 'HK350670', '05/07/2004 07:00:00 PM', '031XX N BROADWAY', '860', 'THEFT', 'RETAIL THEFT', 'SMALL RETAIL STORE', 'FALSE', 'FALSE', 2332, 19, 44, 6, '6', 1171693, 1921311, 2004, '02/10/2018 03:50:01 PM', Decimal('41.93953877'), Decimal('-87.64438351'), '(41.939538767, -87.644383505)'),
 (1516518, 'G256545', '05/04/2001 06:15:00 PM', '045XX S DAMEN AV', '820', 'THEFT', '$500 AND UNDER', 'SMALL RETAIL STORE', 'TRUE', 'FALSE', 914, 9, None, None, '6', 1163610, 1874345, 2001, '08/17/2015 03:03:40 PM', Decimal('41.81083442'), Decimal('-87.67541390'), '(41.810834416, -87.675413895)'),
 (10952376, 'JA272438', '05/20/2017 08:30:00 PM', '028XX W 21ST ST', '820', 'THEFT', '$500 AND UNDER', 'SIDEWALK', 'FALSE', 'FALSE', 1023, 10, 12, 30, '6', 1157493, 1889929, 2017, '02/10/2018 03:50:01 PM', Decimal('41.85372509'), Decimal('-87.69742748'), '(41.853725089, -87.697427476)'),
 (2000970, 'HH201585', '02/22/2002 04:30:00 AM', '024XX N MILWAUKEE AV', '810', 'THEFT', 'OVER $500', 'BAR OR TAVERN', 'FALSE', 'FALSE', 1414, 14, None, None, '6', 1156341, 1915936, 2002, '02/28/2018 03:56:25 PM', Decimal('41.92511408'), Decimal('-87.70095228'), '(41.925114077, -87.700952275)'),
 (1476982, 'G212935', '04/14/2001 03:00:00 PM', '007XX N GREEN ST', '850', 'THEFT', 'ATTEMPT THEFT', 'MOVIE HOUSE/THEATER', 'FALSE', 'FALSE', 1323, 12, None, None, '6', 1170623, 1905487, 2001, '08/17/2015 03:03:40 PM', Decimal('41.89614043'), Decimal('-87.64878026'), '(41.896140428, -87.648780261)'),
 (4273693, 'HL590300', '08/31/2005 03:00:00 AM', '009XX N SACRAMENTO BLVD', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 1311, 12, 26, 23, '6', 1156004, 1906299, 2005, '02/28/2018 03:56:25 PM', Decimal('41.89867615'), Decimal('-87.70245104'), '(41.898676154, -87.702451037)'),
 (4067549, 'HL409680', '06/09/2005 05:00:00 PM', '069XX S SANGAMON ST', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 733, 7, 17, 68, '6', 1171170, 1858915, 2005, '02/28/2018 03:56:25 PM', Decimal('41.76833059'), Decimal('-87.64813561'), '(41.768330593, -87.648135609)'),
 (4718689, 'HM324025', '05/01/2006 03:20:00 PM', '0000X W ELM ST', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 1824, 18, 42, 8, '6', 1175504, 1908078, 2006, '02/10/2018 03:50:01 PM', Decimal('41.90314200'), Decimal('-87.63077557'), '(41.903141995, -87.63077557)'),
 (1845995, 'G662598', '11/03/2001 02:26:55 PM', '0000X N STATE ST', '820', 'THEFT', '$500 AND UNDER', 'DEPARTMENT STORE', 'TRUE', 'FALSE', 122, 1, None, None, '6', 1176398, 1900691, 2001, '08/17/2015 03:03:40 PM', Decimal('41.88285155'), Decimal('-87.62771491'), '(41.882851552, -87.627714909)'),
 (8678872, 'HV353560', '04/15/2012 09:00:00 AM', '072XX S PAXTON AVE', '890', 'THEFT', 'FROM BUILDING', 'RESIDENCE', 'FALSE', 'FALSE', 333, 3, 5, 43, '6', 1192140, 1857319, 2012, '02/04/2016 06:33:39 AM', Decimal('41.76346691'), Decimal('-87.57132336'), '(41.763466911, -87.571323359)'),
 (6855661, 'HR261581', '04/10/2009 05:00:00 PM', '017XX W CERMAK RD', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 1034, 10, 25, 31, '6', 1165218, 1889459, 2009, '02/28/2018 03:56:25 PM', Decimal('41.85227488'), Decimal('-87.66908723'), '(41.852274879, -87.66908723)'),
 (4385612, 'HL680775', '10/14/2005 05:30:00 PM', '017XX N HERMITAGE AVE', '820', 'THEFT', '$500 AND UNDER', 'VEHICLE NON-COMMERCIAL', 'FALSE', 'FALSE', 1433, 14, 32, 24, '6', 1164410, 1911688, 2005, '02/28/2018 03:56:25 PM', Decimal('41.91329017'), Decimal('-87.67142355'), '(41.913290173, -87.671423547)'),
 (4929211, 'HM543491', '06/29/2006 12:00:00 PM', '021XX W ROSCOE ST', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 1913, 19, 32, 5, '6', 1161308, 1922552, 2006, '02/28/2018 03:56:25 PM', Decimal('41.94316683'), Decimal('-87.68251667'), '(41.943166826, -87.682516667)'),
 (9978032, 'HY167451', '02/27/2015 11:00:00 AM', '063XX S YALE AVE', '820', 'THEFT', '$500 AND UNDER', 'SIDEWALK', 'FALSE', 'FALSE', 722, 7, 20, 68, '6', 1175585, 1863128, 2015, '02/10/2018 03:50:01 PM', Decimal('41.77979388'), Decimal('-87.63182661'), '(41.779793875, -87.631826613)'),
 (10190267, 'HY377901', '08/10/2015 09:00:00 PM', '026XX N MILWAUKEE AVE', '810', 'THEFT', 'OVER $500', 'SIDEWALK', 'FALSE', 'FALSE', 1412, 14, 35, 22, '6', 1154504, 1917426, 2015, '02/10/2018 03:50:01 PM', Decimal('41.92923973'), Decimal('-87.70766234'), '(41.929239732, -87.707662339)'),
 (9575333, 'HX225704', '04/16/2014 12:00:00 AM', '002XX W MONROE ST', '890', 'THEFT', 'FROM BUILDING', 'RESTAURANT', 'FALSE', 'FALSE', 122, 1, 2, 32, '6', 1174585, 1899875, 2014, '02/10/2018 03:50:01 PM', Decimal('41.88065311'), Decimal('-87.63439665'), '(41.880653112, -87.634396649)'),
 (2688426, 'HJ308632', '04/17/2003 09:00:00 PM', '017XX N AUSTIN AVE', '810', 'THEFT', 'OVER $500', 'RESIDENCE-GARAGE', 'FALSE', 'FALSE', 2531, 25, 29, 25, '6', 1136138, 1910943, 2003, '02/28/2018 03:56:25 PM', Decimal('41.91179756'), Decimal('-87.77530779'), '(41.911797557, -87.775307788)'),
 (8854340, 'HV528008', '10/20/2012 12:00:00 PM', '029XX N LAKE SHORE DR', '890', 'THEFT', 'FROM BUILDING', 'NURSING HOME/RETIREMENT HOME', 'FALSE', 'FALSE', 1934, 19, 44, 6, '6', 1173772, 1920055, 2012, '02/10/2018 03:50:01 PM', Decimal('41.93604616'), Decimal('-87.63678016'), '(41.936046155, -87.636780157)'),
 (3704662, 'HK801112', '12/10/2004 09:30:00 AM', '055XX S WELLS ST', '810', 'THEFT', 'OVER $500', 'STREET', 'FALSE', 'FALSE', 711, 7, 3, 68, '6', 1175549, 1868101, 2004, '02/10/2018 03:50:01 PM', Decimal('41.79344111'), Decimal('-87.63180984'), '(41.793441113, -87.631809838)'),
 (7724785, 'HS532107', '09/11/2010 11:50:00 PM', '065XX S ST LAWRENCE AVE', '890', 'THEFT', 'FROM BUILDING', 'APARTMENT', 'FALSE', 'FALSE', 321, 3, 20, 42, '6', 1181360, 1861718, 2010, '02/10/2018 03:50:01 PM', Decimal('41.77579347'), Decimal('-87.61069831'), '(41.775793468, -87.61069831)'),
 (10943516, 'JA261898', '05/13/2017 08:05:00 AM', '0000X N LATROBE AVE', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 1522, 15, 28, 25, '6', 1141381, 1899903, 2017, '02/10/2018 03:50:01 PM', Decimal('41.88140727'), Decimal('-87.75631908'), '(41.88140727, -87.756319082)'),
 (11185089, 'JA559176', '12/20/2017 04:30:00 PM', '019XX S MILLARD AVE', '810', 'THEFT', 'OVER $500', 'RESIDENCE', 'FALSE', 'FALSE', 1014, 10, 24, 29, '6', 1152346, 1890287, 2017, '05/04/2018 03:51:04 PM', Decimal('41.85481053'), Decimal('-87.71630954'), '(41.854810528, -87.716309542)'),
 (11072808, 'JA412895', '08/31/2017 03:30:00 AM', '011XX N KARLOV AVE', '810', 'THEFT', 'OVER $500', 'RESIDENTIAL YARD (FRONT/BACK)', 'FALSE', 'FALSE', 1111, 11, 37, 23, '6', 1148843, 1907272, 2017, '02/10/2018 03:50:01 PM', Decimal('41.90148766'), Decimal('-87.72872800'), '(41.901487656, -87.728728004)'),
 (10084732, 'HY273740', '05/24/2015 09:45:00 PM', '004XX N STATE ST', '820', 'THEFT', '$500 AND UNDER', 'BAR OR TAVERN', 'FALSE', 'FALSE', 1831, 18, 42, 8, '6', 1176302, 1903096, 2015, '02/10/2018 03:50:01 PM', Decimal('41.88945317'), Decimal('-87.62799483'), '(41.889453169, -87.627994833)'),
 (10485657, 'HZ224258', '04/12/2016 07:15:00 PM', '017XX N LUNA AVE', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 2532, 25, 37, 25, '6', 1139131, 1911034, 2016, '02/10/2018 03:50:01 PM', Decimal('41.91199331'), Decimal('-87.76431002'), '(41.911993311, -87.764310023)'),
 (2963994, 'HJ652747', '09/26/2003 12:00:00 PM', '022XX W HARRISON ST', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'FALSE', 'FALSE', 1211, 12, 2, 28, '6', 1161653, 1897333, 2003, '02/28/2018 03:56:25 PM', Decimal('41.87395682'), Decimal('-87.68195253'), '(41.873956822, -87.681952527)'),
 (1340847, 'G040244', '01/19/2001 06:39:03 PM', '063XX N NAGLE AV', '820', 'THEFT', '$500 AND UNDER', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 1611, 16, None, None, '6', 1132586, 1941599, 2001, '08/17/2015 03:03:40 PM', Decimal('41.99598354'), Decimal('-87.78763989'), '(41.99598354, -87.787639887)'),
 (2771112, 'HJ415128', '06/08/2003 09:00:00 AM', '037XX S WOLCOTT AVE', '810', 'THEFT', 'OVER $500', 'VEHICLE NON-COMMERCIAL', 'FALSE', 'FALSE', 922, 9, 11, 59, '6', 1164300, 1879991, 2003, '02/28/2018 03:56:25 PM', Decimal('41.82631315'), Decimal('-87.67272382'), '(41.826313153, -87.67272382)'),
 (8861185, 'HV534721', '10/25/2012 08:10:00 PM', '017XX W FULLERTON AVE', '820', 'THEFT', '$500 AND UNDER', 'DEPARTMENT STORE', 'FALSE', 'FALSE', 1811, 18, 32, 7, '6', 1164140, 1915989, 2012, '02/10/2018 03:50:01 PM', Decimal('41.92509811'), Decimal('-87.67229367'), '(41.925098106, -87.672293669)'),
 (11143628, 'JA503725', '11/08/2017 10:38:00 AM', '058XX S ASHLAND AVE', '820', 'THEFT', '$500 AND UNDER', 'STREET', 'TRUE', 'FALSE', 713, 7, 15, 67, '6', 1166676, 1865801, 2017, '02/10/2018 03:50:01 PM', Decimal('41.78732372'), Decimal('-87.66441195'), '(41.787323718, -87.664411954)'),
 (5214424, 'HM803061', '12/31/2006 11:53:00 AM', '029XX N ASHLAND AVE', '860', 'THEFT', 'RETAIL THEFT', 'GROCERY FOOD STORE', 'TRUE', 'FALSE', 1931, 19, 32, 6, '6', 1165142, 1919763, 2006, '02/28/2018 03:56:25 PM', Decimal('41.93543292'), Decimal('-87.66850434'), '(41.935432921, -87.668504341)'),
 (5931425, 'HN731220', '11/21/2007 12:00:00 PM', '003XX S WACKER DR', '890', 'THEFT', 'FROM BUILDING', 'COMMERCIAL / BUSINESS OFFICE', 'FALSE', 'FALSE', 111, 1, 2, 32, '6', 1173916, 1898816, 2007, '02/28/2018 03:56:25 PM', Decimal('41.87776207'), Decimal('-87.63688469'), '(41.877762073, -87.63688469)'),
 (6622100, 'HP691879', '11/17/2008 07:30:00 AM', '046XX S DREXEL BLVD', '820', 'THEFT', '$500 AND UNDER', 'APARTMENT', 'FALSE', 'FALSE', 2123, 2, 4, 39, '6', 1183100, 1874490, 2008, '02/28/2018 03:56:25 PM', Decimal('41.81080062'), Decimal('-87.60392245'), '(41.810800619, -87.603922445)'),
 (8863261, 'HV537004', '10/25/2012 05:00:00 PM', '054XX N ASHLAND AVE', '810', 'THEFT', 'OVER $500', 'OTHER', 'FALSE', 'TRUE', 2012, 20, 40, 77, '6', 1164674, 1936421, 2012, '02/10/2018 03:50:01 PM', Decimal('41.98115315'), Decimal('-87.66975020'), '(41.981153152, -87.669750197)'),
 (6731976, 'HR149903', '02/02/2009 01:00:00 AM', '010XX W BELMONT AVE', '890', 'THEFT', 'FROM BUILDING', 'TAVERN/LIQUOR STORE', 'FALSE', 'FALSE', 1924, 19, 44, 6, '6', 1168964, 1921423, 2009, '02/28/2018 03:56:25 PM', Decimal('41.93990585'), Decimal('-87.65441005'), '(41.939905846, -87.654410045)'),

### Problem 3

##### How many crimes involve an arrest?

In [10]:
%sql select count(*) from chicago_crime_data where arrest = "TRUE"

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('163'),)]

### Problem 4

##### Which unique types of crimes have been recorded at GAS STATION locations?

In [18]:
%sql select DISTINCT(primary_type) from chicago_crime_data WHERE LOCATION_DESCRIPTION ='GAS STATION';

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('CRIMINAL TRESPA',), ('NARCOTICS',), ('ROBBERY',), ('THEFT',)]

Hint: Which column lists types of crimes e.g. THEFT?

### Problem 5

##### In the CENUS_DATA table list all Community Areas whose names start with the letter ‘B’.

In [22]:
%sql select * from CENSUS_DATA where community_area_name LIKE 'B%';

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(19, 'Belmont Cragin', Decimal('10.8'), Decimal('18.7'), Decimal('14.6'), Decimal('37.3'), Decimal('37.3'), 15461, 70),
 (47, 'Burnside', Decimal('6.8'), Decimal('33.0'), Decimal('18.6'), Decimal('19.3'), Decimal('42.7'), 12515, 79),
 (58, 'Brighton Park', Decimal('14.4'), Decimal('23.6'), Decimal('13.9'), Decimal('45.1'), Decimal('39.3'), 13089, 84),
 (60, 'Bridgeport', Decimal('4.5'), Decimal('18.9'), Decimal('13.7'), Decimal('22.2'), Decimal('31.3'), 22694, 43),
 (72, 'Beverly', Decimal('0.9'), Decimal('5.1'), Decimal('8.0'), Decimal('3.7'), Decimal('40.5'), 39523, 12)]

### Problem 6

##### Which schools in Community Areas 10 to 15 are healthy school certified?

In [28]:
%sql select * from CHICAGO_PUBLIC_SCHOOLS where COMMUNITY_AREA_NUMBER between 10 and 15\
AND healthy_school_certified = 'Yes';

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(609995, 'Rufus M Hitch Elementary School', 'ES', '5625 N McVicker Ave', 'Chicago', 'IL', 60646, '(773) 534-1189', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609995.pdf', "O'Hare Elementary Network", 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Level 1', 'Yes', 'Strong', 64, 'Strong', '77', 'Average', 55, 'Average', 58, 'Strong', '65', 'Strong', '70', 'Strong', '55', 'Strong', '54', '95.10%', Decimal('3.7'), '96.60%', '98.60%', '73.7', '27.6', '62.2', '51.7', '50', '67.8', '56.5', '54.8', '52', '63.3', '22.9', '37.5', Decimal('29.5'), Decimal('24.7'), Decimal('-0.1'), Decimal('0.0'), 'Yellow', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 542, 30, 'NDA', Decimal('1134940.195'), Decimal('1937129.571'), Decimal('41.98367756'), Decimal('-87.77908614'), 10, 'NORWOOD PARK', 45, 16, '(41.98367756, -87.77908614)')]

### Problem 7

##### What is the average school Safety Score?

In [29]:
%sql select AVG(safety_score) as AVERAGE_SCRORE from CHICAGO_PUBLIC_SCHOOLS;

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('49.504873'),)]

### Problem 8

##### List the top 5 Community Areas by average College Enrollment [number of students]

In [36]:
%sql select * from chicago_public_schools order by college_enrollment asc fetch first 5 rows only

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(610075, 'Moses Montefiore Special Elementary School', 'ES', '1310 S Ashland Ave', 'Chicago', 'IL', 60608, '(773) 534-7825', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610075.pdf', 'Fulton Elementary Network', 'WEST SIDE COLLABORATIVE', 'NDA', 'Track_E', 'Not Applicable', 'Level 3', 'No', 'Weak', 28, 'NDA', 'NDA', 'Average', 42, 'Very Weak', 14, 'NDA', 'NDA', 'NDA', 'NDA', 'Weak', '46', 'Strong', '54', '80.40%', Decimal('251.6'), '93.50%', '100.00%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '0', '2.9', '35.5', '32.3', '0', '0', Decimal('0.0'), Decimal('0.0'), Decimal('-0.6'), Decimal('-0.1'), 'Yellow', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 21, 38, 'NDA', Decimal('1165892.869'), Decimal('1893999.307'), Decimal('41.86471954'), Decimal('-87.66648084'), 28, 'NEAR WEST SIDE', 2, 12, '(41.86471954, -87.66648084)'),
 (610280, 'Kate S Buckingham Special Education Center', 'ES', '9207 S Phillips Ave', 'Chicago', 'IL', 60617, '(773) 535-6422', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610280.pdf', 'Skyway Elementary Network', 'SOUTH SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not Applicable', 'Level 3', 'No', 'Weak', 31, 'NDA', 'NDA', 'Weak', 24, 'Weak', 20, 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', '83.40%', Decimal('116.9'), '94.40%', '100.00%', 'NDA', 'NDA', '20', '20', '80', '70', '0', '4.3', '45', '59.1', 'NDA', 'NDA', Decimal('0.0'), Decimal('0.0'), Decimal('-0.4'), Decimal('-0.8'), 'Yellow', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 26, 47, 'NDA', Decimal('1194146.741'), Decimal('1844346.869'), Decimal('41.72782129'), Decimal('-87.56439326'), 48, 'CALUMET HEIGHTS', 7, 4, '(41.72782129, -87.56439326)'),
 (610264, 'Walter Reed Elementary School', 'ES', '6350 S Stewart Ave', 'Chicago', 'IL', 60621, '(773) 535-3075', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610264.pdf', 'Englewood-Gresham Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Probation', 'Level 2', 'No', 'Weak', 29, 'NDA', 'NDA', 'Strong', 62, 'Strong', 68, 'NDA', 'NDA', 'NDA', 'NDA', 'Average', '47', 'Average', '51', '92.40%', Decimal('75.5'), '93.20%', '100.00%', 'NDA', 'NDA', '43.2', '34.1', '65.9', '65.9', '66', '20', '93.6', '75.6', '0', '5.3', Decimal('28.6'), Decimal('9.9'), Decimal('2.0'), Decimal('-0.3'), 'Green', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 44, 45, 'NDA', Decimal('1174681.574'), Decimal('1862611.036'), Decimal('41.77839545'), Decimal('-87.63515406'), 68, 'ENGLEWOOD', 20, 7, '(41.77839545, -87.63515406)'),
 (610535, 'Mason High School', 'HS', '4217 W 18th St', 'Chicago', 'IL', 60623, '(773) 534-1530', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610535.pdf', 'West Side High School Network', 'WEST SIDE COLLABORATIVE', 'NDA', 'Standard', 'Not on Probation', 'Not Enough Data', 'No', 'Average', 50, 'NDA', 'NDA', 'Average', 59, 'Average', 59, 'NDA', 'NDA', 'NDA', 'NDA', 'Average', '50', 'Average', '47', '90.40%', Decimal('44.3'), '0.00%', '72.70%', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', None, None, None, None, 'NDA', 'NDA', 'NDA', 'NDA', '12.6', '13.5', 'NDA', '13.9', '1.3', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 48, 36, '40.9', Decimal('1148477.255'), Decimal('1891003.441'), Decimal('41.85685194'), Decimal('-87.73049117'), 29, 'NORTH LAWNDALE', 24, 10, '(41.85685194, -87.73049117)'),
 (610253, 'Julia C Lathrop Elementary School', 'ES', '1440 S Christiana Ave', 'Chicago', 'IL', 60623, '(773) 534-1812', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610253.pdf', 'Austin-North Lawndale Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Standard', 'Probation', 'Level 3', 'No', 'Strong', 67, 'NDA', 'NDA', 'Average', 58, 'Weak', 26, 'NDA', 'NDA', 'NDA', 'NDA', 'Weak', '40', 'Average', '50', '90.50%', Decimal('113.5'), '95.50%', '100.00%', '38.5', 'NDA', '19.5', '13.2', '45.5', '34.1', '18.4', '34.7', '35', '61.1', '7.7', '3.8', Decimal('5.9'), Decimal('4.0'), Decimal('-1.7'), Decimal('-0.6'), 'Red', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 83, 37, 'NDA', Decimal('1154232.147'), Decimal('1892627.172'), Decimal('41.86119482'), Decimal('-87.70932410'), 29, 'NORTH LAWNDALE', 24, 10, '(41.86119482, -87.7093241)')]

### Problem 9

##### Use a sub-query to determine which Community Area has the least value for school Safety Score?

### Problem 10

##### [Without using an explicit JOIN operator] Find the Per Capita Income of the Community Area which has a school Safety Score of 1.

In [37]:
%sql select  COMMUNITY_AREA_NAME,per_capita_income \
from CENSUS_DATA \
where community_area_number = (select community_area_number from CHICAGO_PUBLIC_SCHOOLS where safety_score = 1);

 * ibm_db_sa://wtf02561:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Washington Park', 13785)]

Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).